apiVersion: blaxel.com/v1alpha1
kind: IntegrationConnection
metadata:
  name: openai-integration
spec:
  integration: openai
  secret:
    apiKey: ${secrets.OPENAI_API_KEY}
---
apiVersion: blaxel.com/v1alpha1
kind: Model
metadata:
  name: gpt-4o
  displayName: GPT 4o
spec:
  integrationConnections:
    - openai-integration
  runtime:
    model: gpt-4o
    type: openai
